# Mühendis Dayanışması - GitHub Pages Konfigürasyonu
title: "Mühendis Dayanışması"
description: "Türkiye'deki mühendislerin sosyal ve ekonomik haklarını görünür kılmak için başlatılan kampanya"
baseurl: ""
url: "https://muhendisdayanismasi.github.io"

# Favicon
favicon: "/favicon.svg"

# GitHub Pages tema
remote_theme: pages-themes/minima@v2.5.0
# theme: minima

# Site ayarları
lang: tr-TR
timezone: Europe/Istanbul

# Sosyal medya ve iletişim
github_username: muhendisdayanismasi
# email: Gmail'den muhendisdayanismasi olarak ulaşabilirsiniz (manuel contact için)
# Sosyal medya hesapları yakında aktif olacak
# twitter_username: TBD
# linkedin_username: TBD

# Navigasyon menüsü
header_pages:
  - manifesto.md
  - sss.md
  - referanslar.md
  - kampanya_cercevesi.md
  - iletisim.md
  - yakinda.md
  - test.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build ayarları
markdown: kramdown
highlighter: rouge
permalink: pretty

# İçerik ayarları
show_excerpts: true
excerpt_separator: "<!--more-->"

# SEO ve meta
author: "Mühendis Dayanışması"
logo: /assets/images/logo.png

# Footer
footer_content: "Mühendis Dayanışması © 2025. Bu proje açık kaynak olarak paylaşılmaktadır."

# Exclude files
exclude:
  - TODO.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .gitignore
