# Cayman Test Configuration
# Backup current config
title: "Mühendis Dayanışması"
description: "Türkiye'deki mühendislerin sosyal ve ekonomik haklarını görünür kılmak için başlatılan kampanya"
baseurl: ""
url: "https://muhendisdayanismasi.github.io"

# Cayman theme
theme: cayman

# Site ayarları
lang: tr-TR
timezone: Europe/Istanbul

# Sosyal medya
github_username: muhendisdayanismasi

# Navigasyon menüsü - Cayman için
header_pages:
  - manifesto.md
  - yakinda.md
  - sss.md
  - iletisim.md

# Plugins (minimal for speed)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build ayarları - Performance Optimized  
markdown: kramdown
highlighter: rouge
permalink: pretty
incremental: true

# SASS compression
sass:
  style: compressed

# Exclude files
exclude:
  - TODO.md
  - README.md
  - THEME_COMPARISON.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .github/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
